### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [25]:
import numpy as np

In [26]:
vector = np.random.rand(10)
print("Вектор: \n", vector)
print("Розмірність:", vector.shape)


matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print("\n Матриця:\n", matrix)
print("Розмірність:", matrix.shape)

Вектор: 
 [0.56980501 0.16742445 0.81257159 0.17147575 0.21899829 0.95773786
 0.64433024 0.64879666 0.42367886 0.00149547]
Розмірність: (10,)

 Матриця:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмірність: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [27]:
vector_add10 = np.round(vector + 10, 2)
print("Вектор + 10: ", vector_add10)

matrix_multiply2 = matrix * 2
print("Матриця * 2:\n", matrix_multiply2)

vector_squared = vector ** 2
print("Квадрат вектора:\n", vector_squared)

Вектор + 10:  [10.57 10.17 10.81 10.17 10.22 10.96 10.64 10.65 10.42 10.  ]
Матриця * 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]
Квадрат вектора:
 [3.24677754e-01 2.80309465e-02 6.60272584e-01 2.94039344e-02
 4.79602493e-02 9.17261814e-01 4.15161458e-01 4.20937103e-01
 1.79503776e-01 2.23644206e-06]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [28]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [29]:
result_matrix = np.dot(B, A)
print("Результат множення матриць В на А: \n", result_matrix)

Результат множення матриць В на А: 
 [[0.7281 0.5202]
 [0.2034 0.2846]]


In [31]:
result_matrixC = np.dot(result_matrix, C)
print("Результат множення result_matrix на C:\n", result_matrixC)

Результат множення result_matrix на C:
 [[0.5202]
 [0.2846]]


In [32]:
result_matrixD = np.dot(result_matrix, D)
print("Результат множення result_matrix на D:\n", result_matrixD)

Результат множення result_matrix на D:
 [[0.5202 0.7281]
 [0.2846 0.2034]]


B має розмірність (2, 3), а A - (3, 2), тому B * A матиме розмірність (2, 2).

result_matrix має розмірність (2, 2), а C - (2, 1), тому result_matrix * C матиме розмірність (2, 1).

Матриця D має розмірність (2, 2), тому result_matrix * D матиме розмірність (2, 2).


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [33]:
print("Оригінальна матриця:\n", result_matrix)
result_matrix_t = result_matrix.T
print("\n Транспонована матриця:\n", result_matrix_t)
print("\n Розмірність:", result_matrix_t.shape)

Оригінальна матриця:
 [[0.7281 0.5202]
 [0.2034 0.2846]]

 Транспонована матриця:
 [[0.7281 0.2034]
 [0.5202 0.2846]]

 Розмірність: (2, 2)


In [38]:
print("\n Вектор vector :\n", vector)
print("\n Розмірність:", vector.shape)


 Вектор vector :
 [0.56980501 0.16742445 0.81257159 0.17147575 0.21899829 0.95773786
 0.64433024 0.64879666 0.42367886 0.00149547]

 Розмірність: (10,)


In [34]:
vector_t = vector.T
print("\n Транспонований вектор:\n", vector_t)
print("\n Розмірність:", vector_t.shape)


 Транспонований вектор:
 [0.56980501 0.16742445 0.81257159 0.17147575 0.21899829 0.95773786
 0.64433024 0.64879666 0.42367886 0.00149547]

 Розмірність: (10,)


Зміни не відбулося

In [39]:
print("Оригігнальний вектор:\n", vector)

column_vector = np.expand_dims(vector, axis=1)
print("\n Column vector:\n", column_vector)

Оригігнальний вектор:
 [0.56980501 0.16742445 0.81257159 0.17147575 0.21899829 0.95773786
 0.64433024 0.64879666 0.42367886 0.00149547]

 Column vector:
 [[0.56980501]
 [0.16742445]
 [0.81257159]
 [0.17147575]
 [0.21899829]
 [0.95773786]
 [0.64433024]
 [0.64879666]
 [0.42367886]
 [0.00149547]]


In [41]:
print(vector.shape)
print(column_vector.shape)

(10,)
(10, 1)


In [42]:
column_vector_t = column_vector.T
print("\n Транспонований column vector:\n", column_vector_t)
print("\n Розмірність:", column_vector_t.shape)


 Транспонований column vector:
 [[0.56980501 0.16742445 0.81257159 0.17147575 0.21899829 0.95773786
  0.64433024 0.64879666 0.42367886 0.00149547]]

 Розмірність: (1, 10)
